<a href="https://colab.research.google.com/github/ilvnr999/Notebook/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 基本語法
```import numpy as np```

### 建立ndarray

在後面都可接, dtype設定資料型態 int float bool等

* ```demo = np.array([arg1, arg2, ...])``` 一維陣列

* ```demo2 = np.array([[1, 2, 3], [4, 5, 6]])``` 二維陣列

* ```demo3 = np.array([[[1, 2, 3],[4, 5 ,6]],[[7, 8, 9], [10, 11, 12]]])``` 三維陣列
* ```np.zeros((2,3))``` 建立2x3為0的陣列

* ```np.ones((2, 3, 4))``` 建立2x3x4為1的陣列

* ```np.empty((2x3))``` 建立2x3無初始值的陣列

* ```np.full((3,2), 8)``` 建立一個3x2 值皆為8的陣列

* ```np.eye(2)``` 建立2x2的單位矩陣（可不為矩形多出的補0）

* ```np.arange(1, 10, 2)``` 建立由1開始 不超過10 間隔為2的均勻數值一維陣列

* ```np.linsapce(1, 10, 5)``` 建立0到10之間 均勻的五個數值的一維陣列

random

* ```rng = np.random.default_rng()``` 建立2x3的隨機矩陣 新
  
  ```rng.random(（2, 3))```

* ```np.random.random((2, 3))``` 建立2x3的隨機矩陣

  ```np.random.ranf((2, 3))```

  ```np.random.sample((2, 3))```

* ```np.random.randint(1, 15, (2, 3))``` 2x3的從1到15隨機整數陣列
   
  ```np.random.randint(1, 15, 10)``` 建立一維10個數字1到15的陣列

* ```np.random.normal(3, 2, (5, 2))``` 5x2的平均值為3標準差為2的陣列

### Inspecting 查察

* ```arg.shape``` 陣列形狀 （row, columns）

* ```len(arg)``` 陣列長度( )的第一個數字

* ```arg.ndim``` 陣列的維度

* ```arg.size``` 元素數量

* ```arg.dtype``` 元素的資料型態

* ```arg.dtype.name``` 資料型態的名稱

* ```arg.astype(dtype)``` 將arg的資料轉為其他資料型態

### Comparison

依照元素比較輸入輸出相同shape但輸出為bool 僅有array_equal是對比整個array會輸出一個bool

* ```arg1 == agr2```

* ```arg < 2```

* ```np.array_equal(arg1, arg2)```

###Aggregate Functions 聚合函數

* ```demo.max()``` 最大值 data.max(axis=0) 找該方向的最大值（每個columns的最大值）

* ```demo.min()``` 最小值  

* ```demo.sum()``` 所有元素的和

* ```demo.max(axis=0/1)``` axis不同方向的最大最小陣列

* ```demo.median(demo)``` 中位數

* ```demo.mean(demo)``` 平均數

* ```np.std(demo)``` 標準差

* ```demo.argmax()``` 最大值對應的index

* ```demo.argmin()``` 最小值對應的index

### 複製與排序

* ```arg.sort()``` 由小排到大 直接改變原本變數

* ```np.sort(arg)``` 回傳由小排到大的資料

* ```np.argsort(arg)``` 回傳陣列由小排到大後的index 相同位子的元素在排列後的index

* ```arg.copy()``` 拷貝

### Subsetting, Slicing, Indexing

```a = np.array([1, 2, 3, 4])```

```b = np.array([2.5, 1, 3, 4.5], [5, 6 ,7 ,8])```

* ```a[2]``` 3

* ```b[1, 3]``` 8.0 **支援多維度的資料型態可以直接使用此方法取出值[a, b] list則需要透過[a][b] 效率較低**

slicing (會影響原本的array)

* ```a[0:2]``` array([1, 2])

* ```b[0:2, 1]``` array([1., 6.])

boolean indexing

* ```a[a<4]``` array([1, 2, 3])

fancy indexing

* ```b[[1, 1, 0, 0], [0, 2, 1, 0]]``` array([5., 7., 1, 2.5]) 依照[ ]內的行列取值

### 陣列操作

transposing array

* ```b.T``` 轉置 (僅適用二維陣列)

  ```b.transpose()````

* ```col = a[:,np.newaxis]``` 一維陣列適用之轉置 （1,6）

* ```row = a[np.newaxis, :]``` 多增加一個維度 （6,1）

changing array shape

* ```b.ravel()``` array([2.5, 1, 3, 4.5, 5, 6 ,7 ,8]) 將array攤平成一維向量

* ```b.flatten()``` 相較於ravel()不會影響原本的array

* ```b.reshape(4, 2)``` array([[2.5, 1], [3, 4.5], [5, 6], [7, 8]])

adding / removeing elements

 ```a = np.array([1, 2, 3, 4])```

 ```b = np.array([6, 7, 8, 9])```

* ```np.append(a, 5)``` array([1, 2, 3, 4, 5]) 在尾段增加元素

* ```np.append(a, b)``` array([1, 2, 3, 4, 6, 7, 8, 9]) 在尾段加入另一個array的元素

* ```np.insert(a, 1, 0)``` array([1, 0, 3, 4]) 將a的第1個元素改為0

* ```np.delete(b, [2])``` array([6, 7, 9]) 將b的第2個元素刪除

* ```np.flip(a, axis)``` 方向相反 可指定axis

* ```a.resize((2, 2))``` array([[1, 2], [3, 4]])
  
reshape VS. resize

* reshape 修改前與後需相同元素數量，回傳一個新的array不改變原本的array

* resize 元素數兩可以不相同，多出截斷，少則重複原本的內容填滿，np.rasize()回傳新的array，arg.resize()則會改變原本的array

combining arrays

 ```a = np.array([[1, 2], [3, 4]])```

 ```b = np.array([[5, 6], [7, 8]])```

* ```np.concatenate(a, b, axis=0)``` = ```np.vstack(a, b)```

  以axis為0的方向垂直運作

  array([[1, 2], [3, 4], [5, 6], [7, 8]])

* ```np.concatenate(a, b, axis=1)``` = ```np.hstack(a, b)```

  以axis為1的方向水平運作

  array([[1, 2, 5, 6], [3, 4, 7, 8]])

spliting array

```a = np.array([[1, 2, 3, 4, 5, 6],[-1, -2, -3, -4, -5, -6], [2, 4, 6, 8, 10, 12]])```

* ```np.split(a, 3, axis=0)``` = ```np.vsplit(a, 3)```

  axis為0的方向垂直運作 切成3個

  array([1, 2, 3, 4, 5, 6]), array([-1, -2, -3, -4, -5, -6]), array([2, 4, 6, 8, 10, 12])

* ```np.split(a, 2, axis=1)``` = ```np.hsplit(a, 2)```

  axis為1的方向水平運作 切成2個

  array([[1, 2, 3], [-1, -2, -3], [2, 4, 6]]), array([[4, 5, 6],[-4, -5, -6], [8, 10, 12]])

* ```np.array_split(a, 4, axis=1)``` 不等量分割

  array([[ 1,  2],[-1, -2],[ 2,  4]]),array([[ 3,  4],[-3, -4],[ 6,  8]]),array([[ 5],[-5],[10]]),array([[ 6],[-6],[12]])

找array所有不同的元素

* ```a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])```

  ```unique_values = np.unique(a)``` [11 12 13 14 15 16 17 18 19 20]



### 四則運算

輸入跟輸出為相同shape

* ```np.add(arg1, arg2)``` 元素相加 （直接兩個函數arg1 + arg2）

* ```np.subtract(arg1, arg2``` 元素相減（直接兩個函數arg1 - arg2）

* ```np.multiply(arg1, arg2)``` 元素相乘（直接兩個函數arg1 * arg2）

* ```np.divide``` 元素相除（直接兩個函數arg1 / arg2）

broadcasting

* ```arg * 1.6``` 所有元素皆乘1.6

* ```arg / 1.6``` 所有元素皆除以1.6

* ```arg ** 1.6``` 所有元素皆1.6次方

### I/O

* ```np.save('file_name.npy', np_object)``` 將物件儲存為.npy檔

* ```np.savetxt('file_name.txt', np_object)``` 將物件儲存為.txt檔或.csv

* ```arg = np.load('file_name.npy')``` 載入.npy檔

* ```arg = np.load('file_name.txt')``` 載入.txt檔或.csv

### Data Types

* b   # 布林數
* i   # 有好整數
* u   # 無號整數
* f   # 浮點數
* c   # 複數浮點數
* O   # pyhton對象
* U   # Unicode
* V   # 原始數據