<a href="https://colab.research.google.com/github/ilvnr999/Notebook/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#pytorch

## 建立Tensor

1. 直接透過list建立

In [2]:
import torch
data = [[1, 2, 3, 4, 5],[2, 3, 4, 5, 6]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6]])


2. 透過np.array建立

In [4]:
import numpy as np
np_array = np.array(data)
x_np = torch.tensor(np_array)
print(x_np)

tensor([[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6]])


3. 透過其他tensor
  
  * 建立元素為1的tensor但保留 (shpae, dtype)

  * 建立隨機元素的tensor保留 shpae

In [10]:
x_one = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"x_one: \n {x_one} \n")
print(f"x_rand: \n {x_rand} \n")

x_one: 
 tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]) 

x_rand: 
 tensor([[0.3189, 0.1898, 0.3436, 0.6113, 0.0725],
        [0.0088, 0.9857, 0.7153, 0.9603, 0.3348]]) 



4. 建立其他tensor

In [9]:
shape = (3, 4)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"rand \n {rand_tensor} \n")
print(f"ones \n {ones_tensor} \n")
print(f"zeros \n {zeros_tensor} \n")

rand 
 tensor([[0.7628, 0.3463, 0.9607, 0.0434],
        [0.9998, 0.0603, 0.5676, 0.8199],
        [0.0825, 0.5720, 0.4457, 0.2555]]) 

ones 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

zeros 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) 



### 屬性

* ```arg.shape```  tensor的shape
* ```arg.dtype```  tensor的元素資料型態
* ```arg.device``` 儲存處

### 張量運算

cuda 確認可用性, 將張量移動到GPU
```
if torch.cuda.is_avalable():
    arg = arg.to("cuda")
```

mps 確認可用性, 將張量移動到GPU(MPS)
```
if torch.backends.mps.is_available():  
    tensor = tensor.to("mps")  
```

### indexing & slicing

### 運算

* ```t1 = torch.cat([arg1, arg2, arg3], dim=1)```  依照dim的方向將tensor連接

tensor 與自己相乘

* ```y1 = arg1 @ arg.T```

* ```y2 = torch.matmul(arg1.T, arg)``` or ```torch.matmul(arg1.T, arg, out=y2)```


In [17]:
import torch
arg1 = torch.tensor([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])

y1 = arg1 @ arg1.T
print(y1)

tensor([[ 55, 130],
        [130, 330]])
